### ISSUE TITLE
Rename FileLockError Enum to Reflect Both Success and Error States

### ISSUE THREAD

**Issue by Omer-Faruk-Dursun** [KaganCanSit/Cross-Compatible-FileLock-Windows-and-Linux#1]
The current enum defined in the file IFileLock.h has a name (**FileLockError**)  that is somewhat misleading as it suggests that the enum only represents error states. However, the enum also includes a status for successful file lock/unlock operations (**FileLockError::OK**).

It would be more intuitive to rename the enum to something that encompasses both successful and error outcomes. Suggested names could be **FileLockStatus** or **FileLockResult**.

**Comment by KaganCanSit** [comment]
Thanks for the feedback. I hadn't considered naming it this way during development. Because at first I was using basic value returns. That's why I based it on zero returns. I will edit it as soon as possible.

**Comment by KaganCanSit** [comment]
I changed the naming to "FileLockStatus". @Omer-Faruk-Dursun  ✔️
Thanks again.
